version: "3.6"

services:
  eu-revenues-dashboard:
    build:
      context: .
    container_name: dash
    #command: python first_run.py
    command: python index.py
    volumes:
      - .:/home/python/app
    ports:
      - "8050:8050"
     
